#!/bin/sh -ex

DB_NAME=typo3
DB_USER=typo3
DB_PASS=$(mcookie)

ADMIN_NAME=admin
ADMIN_PASS=turnkey1

WEBROOT=/var/www/typo3

CONF=/etc/php5/apache2/php.ini

sed -i -e "\
    s|^;\? \?\(upload_max_filesize =\) .*$|\1 10M|; \
    s|^;\? \?\(memory_limit =\) .*$|\1 64M|; \
    s|^;\? \?\(max_execution_time =\) .*$|\1 240|; \
    s|^;\? \?\(max_input_vars =\) .*$|\1 1500|; \
    s|^;\? \?\(memory_limit =\) .*$|\1 128M|; \
    s|^;\? \?\(always_populate_raw_post_data =\) .*$|\1 -1| \
" $CONF

sed -i -e "s|^;\? \?\(memory_limit =\) .*$|\1 128M|;" /etc/php5/cli/php.ini

# configure apache
a2dissite 000-default
a2ensite typo3
a2enmod rewrite
a2enmod expires

# start services
service mysql start
service apache2 start

# setup the database
MYSQL_BATCH="mysql --user=root --password=$MYSQL_PASS --batch"
MYSQL_ADMIN="mysqladmin --user=root --password=$MYSQL_PASS"

$MYSQL_ADMIN create $DB_NAME
$MYSQL_BATCH --execute "grant all privileges on $DB_NAME.* to $DB_USER@localhost identified by '$DB_PASS'; flush privileges;"

cd $(dirname $WEBROOT)

composer create-project typo3/cms-base-distribution='^7.6.0' typo3 --no-interaction || true
# work around issue "Your configuration does not allow connection to http://composer.typo3.org..."
cd $WEBROOT
sed -i "s|http://composer.typo3.org/|https://composer.typo3.org/|" composer.json
composer update typo3/cms

composer require helhum/typo3-console
composer require typo3-ter/introduction

ln -s $WEBROOT/vendor/bin/typo3cms .

./typo3cms install:setup --non-interactive TRUE --database-user-name "$DB_USER" --database-user-password "$DB_PASS" --database-host-name localhost --database-name "$DB_NAME" --use-existing-database --admin-user-name "$ADMIN_NAME" --admin-password "$ADMIN_PASS" --site-name "TurnKey TYPO3"
./typo3cms extension:activate bootstrap_package
./typo3cms extension:activate introduction
./typo3cms extension:setupactive

composer dump-autoload --optimize

chown -R www-data:www-data $WEBROOT/
rm -f $WEBROOT/_.htaccess

# stop services
service mysql stop
service apache2 stop

