#!/bin/bash -e
# regenerate typo3 secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/typo3/typo3conf/localconf.php

ENCKEY=$(mcookie)$(mcookie)$(mcookie)
sed -i "s|encryptionKey.*|encryptionKey'] = '$ENCKEY';|" $CONF

PASSWORD=$(mcookie)
sed -i "s|db_password.*|db_password = '$PASSWORD';|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=typo3 --pass="$PASSWORD"

