#!/bin/bash -e
# regenerate typo3 secrets and mysql password

. /etc/default/inithooks

CONF=/var/www/typo3/typo3conf/LocalConfiguration.php

ENCKEY=$(mcookie)$(mcookie)$(mcookie)
sed -i "s|\('encryptionKey' =>\) .*|\1 '$ENCKEY',|" $CONF

PASSWORD=$(mcookie)
sed -i "s|\('password' =>\) .*|\1 '$PASSWORD',|" $CONF
$INITHOOKS_PATH/bin/mysqlconf.py --user=typo3 --pass="$PASSWORD"

