#!/bin/bash -e
# set typo3 admin password

. /etc/default/inithooks

[ -e $INITHOOKS_CONF ] && . $INITHOOKS_CONF
$INITHOOKS_PATH/bin/typo3.py --pass="$APP_PASS" --email="$APP_EMAIL"

# Recover web and database services after certificate and credential rotation.
systemctl start mariadb apache2
